# SQLite version 3.x
#   gem install sqlite3-ruby (not necessary on OS X Leopard)
development:
  adapter: mysql
  encoding: utf8
  database: blocks_dev
  pool: 5
  username: root
  password:
  socket: /var/lib/mysql/mysql.sock
  host: 127.0.0.1

test:
  adapter: mysql
  encoding: utf8
  database: blocks_test
  pool: 5
  username: root
  password:
  socket: /var/lib/mysql/mysql.sock
  host: 127.0.0.1
